// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TestSubProto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Test
{

	/// <summary>Holder for reflection information generated from TestSubProto.proto</summary>
	public static partial class TestSubProtoReflection
	{

		#region Descriptor
		/// <summary>File descriptor for TestSubProto.proto</summary>
		public static pbr::FileDescriptor Descriptor
		{
			get { return descriptor; }
		}
		private static pbr::FileDescriptor descriptor;

		static TestSubProtoReflection()
		{
			byte[] descriptorData = global::System.Convert.FromBase64String(
				string.Concat(
				  "ChJUZXN0U3ViUHJvdG8ucHJvdG8SCGNvbS50ZXN0Ih8KDFRlc3RTdWJQcm90",
				  "bxIPCgdhY2NvdW50GAEgASgJYgZwcm90bzM="));
			descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
				new pbr::FileDescriptor[] { },
				new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
			new pbr::GeneratedClrTypeInfo(typeof(global::Com.Test.TestSubProto), global::Com.Test.TestSubProto.Parser, new[]{ "Account" }, null, null, null)
				}));
		}
		#endregion

	}
	#region Messages
	public sealed partial class TestSubProto : pb::IMessage<TestSubProto>
	{
		private static readonly pb::MessageParser<TestSubProto> _parser = new pb::MessageParser<TestSubProto>(() => new TestSubProto());
		private pb::UnknownFieldSet _unknownFields;
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		public static pb::MessageParser<TestSubProto> Parser { get { return _parser; } }

		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		public static pbr::MessageDescriptor Descriptor
		{
			get { return global::Com.Test.TestSubProtoReflection.Descriptor.MessageTypes[0]; }
		}

		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		pbr::MessageDescriptor pb::IMessage.Descriptor
		{
			get { return Descriptor; }
		}

		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		public TestSubProto()
		{
			OnConstruction();
		}

		partial void OnConstruction();

		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		public TestSubProto(TestSubProto other) : this()
		{
			account_ = other.account_;
			_unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
		}

		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		public TestSubProto Clone()
		{
			return new TestSubProto(this);
		}

		/// <summary>Field number for the "account" field.</summary>
		public const int AccountFieldNumber = 1;
		private string account_ = "";
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		public string Account
		{
			get { return account_; }
			set
			{
				account_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
			}
		}

		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		public override bool Equals(object other)
		{
			return Equals(other as TestSubProto);
		}

		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		public bool Equals(TestSubProto other)
		{
			if (ReferenceEquals(other, null))
			{
				return false;
			}
			if (ReferenceEquals(other, this))
			{
				return true;
			}
			if (Account != other.Account) return false;
			return Equals(_unknownFields, other._unknownFields);
		}

		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		public override int GetHashCode()
		{
			int hash = 1;
			if (Account.Length != 0) hash ^= Account.GetHashCode();
			if (_unknownFields != null)
			{
				hash ^= _unknownFields.GetHashCode();
			}
			return hash;
		}

		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		public override string ToString()
		{
			return pb::JsonFormatter.ToDiagnosticString(this);
		}

		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		public void WriteTo(pb::CodedOutputStream output)
		{
			if (Account.Length != 0)
			{
				output.WriteRawTag(10);
				output.WriteString(Account);
			}
			if (_unknownFields != null)
			{
				_unknownFields.WriteTo(output);
			}
		}

		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		public int CalculateSize()
		{
			int size = 0;
			if (Account.Length != 0)
			{
				size += 1 + pb::CodedOutputStream.ComputeStringSize(Account);
			}
			if (_unknownFields != null)
			{
				size += _unknownFields.CalculateSize();
			}
			return size;
		}

		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		public void MergeFrom(TestSubProto other)
		{
			if (other == null)
			{
				return;
			}
			if (other.Account.Length != 0)
			{
				Account = other.Account;
			}
			_unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
		}

		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		public void MergeFrom(pb::CodedInputStream input)
		{
			uint tag;
			while ((tag = input.ReadTag()) != 0)
			{
				switch (tag)
				{
					default:
						_unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
						break;
					case 10:
						{
							Account = input.ReadString();
							break;
						}
				}
			}
		}

	}

	#endregion

}

#endregion Designer generated code
